title: Angelina Jude 
description: "ğŸ” Finance Enthusiast | Problem Solver | Data Nerd

 . I believe every number tells a story
 Letâ€™s uncover the insights together.

â˜• Always up for a discussion on markets, investments,
and fintech!  

ğŸ“§ angelinajude4@gmail.com | ğŸ“ +1(408)-396-4354  

ğŸ”— [LinkedIn](https://www.linkedin.com/in/angelinajude/)"

logo: /Profie.jpg
show_downloads: true
theme: jekyll-theme-minimal
